import {
  Accessibility,
  Bath,
  Building2,
  Bus,
  Droplet,
  Dumbbell,
  Flower,
  Lock,
  Luggage,
  Shirt,
  Toilet,
  TrendingDown,
  Umbrella,
  UtensilsCrossed,
  Waves,
  WavesLadder,
  Wine,
} from "lucide-react";
import { ReactNode } from "react";

export const amenityIcons: Record<string, ReactNode> = {
  drink: <Wine className="size-5" />,
  food: <UtensilsCrossed className="size-5" />,
  cabana: <Umbrella className="size-5" />,
  pool: <WavesLadder className="size-5" />,
  "fitness-center": <Dumbbell className="size-5" />,
  beach: <Umbrella className="size-5" />,
  towels: <Shirt className="size-5" />,
  showers: <Droplet className="size-5" />,
  "luggage-storage": <Luggage className="size-5" />,
  restrooms: <Toilet className="size-5" />,
  spa: <Flower className="size-5" />,
  "rooftop-pool": <Building2 className="size-5" />,
  hottub: <Bath className="size-5" />,
  lockers: <Lock className="size-5" />,
  lazyriver: <Waves className="size-5" />,
  waterslide: <TrendingDown className="size-5" />,
  wheelchair: <Accessibility className="size-5" />,
  "airport-shuttle": <Bus className="size-5" />,
};
