import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const basetica = localFont({
  src: [
    {
      path: "../fonts/BaseticaTrial-Regular.otf",
      weight: "400",
    },
    {
      path: "../fonts/BaseticaTrial-Medium.otf",
      weight: "500",
    },
    {
      path: "../fonts/BaseticaTrial-Bold.otf",
      weight: "700",
    },
  ],
  variable: "--font-basetica",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${basetica.variable} antialiased`}>{children}</body>
    </html>
  );
}
